extends: .github
shared:
  DefaultQueueOptions: &DefaultQueueOptions
    commit_message_format:
      title: pr-title
      body: pr-body
    merge_method: squash
  CheckRuns: &CheckRuns
    - check-success=ci-gate
  DefaultReviewCond: &DefaultReviewCond
    - "#approved-reviews-by>=2"
    - author = dependabot[bot]

queue_rules:
  - name: automated updates
    <<: *DefaultQueueOptions
    queue_conditions:
      - base = main
      - author = dependabot[bot]
      - and: *CheckRuns
    merge_conditions:
      - and: *CheckRuns
    merge_method: fast-forward
    batch_size: 7
    batch_max_wait_time: 5min
    commit_message_format:
  - name: default
    <<: *DefaultQueueOptions
    queue_conditions:
      - and: *CheckRuns
    merge_conditions:
      - and: *CheckRuns

pull_request_rules:
  - name: request review
    conditions:
      - -author=dependabot[bot]
      - -merged
      - -closed
      - and: *CheckRuns
      - "#changes-requested-reviews-by=0"
      - review-requested!=@devs
      - not:
          or: *DefaultReviewCond
    actions:
      request_reviews:
        teams:
          - devs

merge_protections:
  - name: 🤖 Continuous Integration
    if: []
    success_conditions:
      - and: *CheckRuns

  - name: 👀 Review Requirements
    if: []
    success_conditions:
      - or: *DefaultReviewCond

merge_protections_settings:
  reporting_method: deployments
  auto_merge_conditions: true
