extends: .github
shared:
  DefaultQueueOptions: &DefaultQueueOptions
    commit_message_template: |
      {{ title }} (#{{ number }})

      {{ body }}
    merge_method: squash
  CheckRuns: &CheckRuns
    - check-success=test
    - check-success=actionlint

queue_rules:
  - name: automated updates
    <<: *DefaultQueueOptions
    autoqueue: true
    queue_conditions:
      - base = main
      - author = dependabot[bot]
      - and: *CheckRuns
    merge_conditions:
      - and: *CheckRuns
    merge_method: merge
    batch_size: 7
    batch_max_wait_time: 5min
    commit_message_template:
    queue_branch_merge_method: fast-forward

  - name: default
    autoqueue: true
    <<: *DefaultQueueOptions
    queue_conditions:
      - and: *CheckRuns
      - "#approved-reviews-by>=2"
      - "#changes-requested-reviews-by=0"
      - "#review-threads-unresolved=0"
      - "#review-requested=0"
    merge_conditions:
      - and: *CheckRuns

pull_request_rules:
  - name: request review
    conditions:
      - -author=dependabot[bot]
      - -draft
      - -closed
      - and: *CheckRuns
      - "#approved-reviews-by=0"
      - "#changes-requested-reviews-by=0"
      - "review-requested!=@devs"
    actions:
      request_reviews:
        teams:
          - devs

merge_protections:
  - name: Required Reviews
    if: []
    success_conditions:
      - or:
        - "#approved-reviews-by >= 2"
        - author = dependabot[bot]

merge_protections_settings:
  reporting_method: deployments
