// Matches timestamps generated by the Mergify engine in merge queue reports.
export const MERGIFY_TIMESTAMP_REGEX =
    /^(\d{4}-\d{2}-\d{2}) (\d{2}:\d{2}) UTC$/;
export const TIMESTAMP_CONVERTED_ATTR = "data-mergify-local-time";

const LOCAL_TIME_FORMATTER = new Intl.DateTimeFormat(undefined, {
    year: "numeric",
    month: "short",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
    timeZoneName: "short",
});

export function formatLocalTime(date) {
    return LOCAL_TIME_FORMATTER.format(date);
}

export function isMergifyBotComment(container) {
    const authorLink = container.querySelector(
        'a.author[href="/apps/mergify"]',
    );
    if (authorLink) return true;

    const avatar = container.querySelector("img.avatar");
    if (avatar && /mergify/i.test(avatar.getAttribute("src") || "")) {
        return true;
    }

    return false;
}

export function getPullRequestData() {
    const url = new URL(window.location.href);
    const parts = url.pathname.split("/");
    return {
        org: parts[1],
        repo: parts[2],
        pull: parts[4],
        subpath: parts[5] || "",
    };
}

export function isGitHubPullRequestPage() {
    const url = new URL(window.location.href);
    const parts = url.pathname.split("/");
    return parts.length >= 5 && parts[3] === "pull";
}

export function findFirstElement(selectors) {
    for (const sel of selectors) {
        const el = document.querySelector(sel);
        if (el) return el;
    }
    return null;
}

export function findTimelineActions() {
    const mergeBoxDiv = document.querySelector(
        "div[class=discussion-timeline-actions]",
    );
    return mergeBoxDiv;
}

export const PR_STATUS_SELECTORS = [
    { selector: 'span[data-status="draft"]', status: "draft" },
    { selector: 'span[data-status="pullOpened"]', status: "open" },
    { selector: 'span[data-status="pullMerged"]', status: "merged" },
    { selector: 'span[data-status="pullClosed"]', status: "closed" },
];

const LEGACY_STATE_BADGE_STATUSES = {
    open: "open",
    draft: "draft",
    merged: "merged",
    closed: "closed",
};

// The single place the PR state is read, for the page itself and for pages
// fetched to resolve another PR's status. Returns null when the scope carries
// no readable state — callers decide what to assume.
export function readPrStatusFromDocument(scope) {
    for (const { selector, status } of PR_STATUS_SELECTORS) {
        if (scope.querySelector(selector)) return status;
    }

    // A data-status pill anywhere means this DOM generation labels the viewed
    // PR that way, so the legacy badge below belongs to a cross-referenced PR
    // (a queued PR's timeline shows its batch PR's badge) and must not be read
    // as this one's state.
    if (scope.querySelector("span[data-status]")) return null;

    const legacyBadge = scope.querySelector("span.State");
    if (legacyBadge) {
        const label = legacyBadge.getAttribute("title")?.split(": ")[1];
        if (!label) {
            console.warn("Can't find pull request status");
            return null;
        }
        return LEGACY_STATE_BADGE_STATUSES[label.toLowerCase()] ?? null;
    }

    return null;
}
